command_timeout=750

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol=" tag "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[$duration ]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = "git "

[golang]
format = '\[[$symbol($version)]($style)\]'
symbol = "go "

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'
symbol = "memory "

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'
symbol = "nix "

[nodejs]
format = '\[[$symbol($version)]($style)\]'
symbol = "node "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
symbol = "ocaml "

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = "python "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = "rust "

[scala]
format = '\[[$symbol($version)]($style)\]'
symbol = "scala "

[terraform]
format = '\[[$symbol$workspace]($style)\]'
symbol = "terraform "

[time]
format = '\[[$time]\]'

[username]
format = '\[[$user]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
symbol = "zig "
